#!/bin/sh
rm -rf /usr/share/enigma2/KravenFHD
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/KravenFHD
rm -rf /usr/lib/enigma2/python/Components/Converter/KravenFHD*
rm -rf /usr/lib/enigma2/python/Components/Renderer/KravenFHD*
echo "                                                          "
echo "              ...Skin successful removed.                 "
echo "                                                          "
