#!/bin/sh
echo "                                                           "
echo "        The Skin KravenFHD is now being installed...       "
echo "                                                           "
