#!/bin/sh
echo "Checking for previous installations..."
if [ -d /usr/share/enigma2/KravenFHD/graphics ]; then
    mkdir /tmp/graphics
    cp /usr/share/enigma2/KravenFHD/graphics/*.* /tmp/graphics
fi
if [ -f /usr/lib/enigma2/python/Plugins/Extensions/KravenFHD/data/skin-user.xml ]; then
    cp /usr/lib/enigma2/python/Plugins/Extensions/KravenFHD/data/skin-user.xml /tmp
fi
if [ -f /usr/share/enigma2/KravenFHD/skin.xml ]; then
    rm -rf /usr/share/enigma2/KravenFHD/skin.xml
fi
echo "                                                           "
echo "        The Skin KravenFHD is now being installed...        "
echo "                                                           "
